// Ready translated locale messages
// The structure of the locale message is the hierarchical object structure with each locale as the top property

const messages = {
    en: {
      common: {
        app_name: "Airticler",
        author_name: "Sergey Sidorov",
        created_date: "2025",
        signin_button_title: "Login",
        logout_button_title: "Logout",
        profile_button_title: "Profile",
        project_button_title: "Projects",
        refresh_button_title: "Refresh",
        tokens_label: "Balance",
      },
      home: {
        app_title: "Bass Liner: explore your favorite bass tabs",
        app_description: "AI platform for extracting bass tabs from your favorite songs"
      },
      login: {
        back_to_home: "Back to home",
        subtitle: "Sign in to start creating amazing content",
        welcome_back: "Welcome back",
        continue_with_account: "Continue with your PM Moscow Club account",
        sign_in_button: "Sign in with PM Moscow Club",
        terms_notice: "By signing in, you agree to our Terms of Service and Privacy Policy",
      },
      new_project: {
        back_to_projects: "Back to Projects",
        title: "Create New Project",
        subtitle: "Start a new writing project with AI assistance",
        form: {
          project_title_label: "Project Title",
          project_title_placeholder: "Enter your project title...",
          description_label: "Theme of post",
          description_placeholder: "Enter the theme of your post...",
          description_hint: "Describe the main theme or topic of your post",
          language_label: "Post Language",
        },
        actions: {
          cancel: "Cancel",
          create: "Create Project",
          creating: "Creating...",
        },
        toast: {
          title_required: "Please enter a project title.",
          description_required: "Please enter the theme of your post.",
          project_created: "Your new project has been created successfully.",
        },
      },
      project_list: {
        title: "My Projects",
        subtitle: "Manage and organize your writing projects",
        new_project_button: "New Project",
        search_placeholder: "Search projects...",
        stats: {
          total: "Total:",
          unpublished: "Unpublished:",
          published: "Published:",
        },
        loading: "Loading projects...",
        error_message: "Failed to load projects. Please try again later.",
        retry_button: "Retry",
        empty_search: "No projects found matching your search.",
        empty_search_title: "No Results Found",
        empty_state: "No projects yet. Create your first project to get started!",
        empty_state_title: "Start Your First Project",
      },
      project_view: {
        loading: "Loading project...",
        loading_text: "Loading post content...",
        sections: {
          data_sources: "Data Sources",
          ai_assistant: "AI Assistant",
          post_content: "Post Content",
        },
        actions: {
          back_to_projects: "Back to projects",
          retry: "Retry",
          upload_pdf: "Upload PDF",
          upload_document: "Upload Document",
          add_text: "Add Text",
          add_pdf_url: "Add PDF URL",
          add_pdf: "Add PDF",
          cancel: "Cancel",
          add_to_rag: "Add to RAG",
          save_post: "Save Post",
          delete_project: "Delete Project",
          refresh_text: "Refresh text from server",
          open_in_modal: "Open in editor",
          refresh: "Refresh",
          uploading: "Uploading...",
          saving: "Saving...",
        },
        placeholders: {
          text_to_add_to_knowledge_base: "Enter text to add to your knowledge base...",
          text_name: "Text name (required)",
          pdf_name: "PDF name (required)",
          pdf_url: "Enter PDF URL (e.g., https://example.com/document.pdf)",
          chat_input: "Ask a question or enter a prompt...",
          post_editor: "Start writing your post here... Use the AI assistant to help generate content based on your data sources.",
        },
        validation: {
          invalid_url: "Please enter a valid URL",
        },
        empty: {
          no_data_sources: "No data sources added yet",
          chat_prompt: "Ask questions about your data sources or get help with your content",
        },
        data_sources: {
          text_snippet_name: "Text snippet",
        },
        post: {
          characters: "{count} characters",
        },
        defaults: {
          unknown_project: "Unknown project",
          untitled_project: "Untitled Project",
          no_description: "No description",
        },
        errors: {
          failed_to_load_project_title: "Failed to load project",
          unknown_error: "Unknown error",
          unknown_error_occurred: "Unknown error occurred",
          project_id_missing: "Project ID is missing",
          failed_to_load_text: "Failed to load post content. You can still edit manually.",
        },
        toast: {
          failed_to_load_project: "Failed to load project",
          file_added_to_sources: "{fileName} has been added to your data sources.",
          text_added_to_rag: "Your text has been added to the RAG knowledge base.",
          pdf_url_added: "PDF URL has been added to your data sources.",
          invalid_url: "Please enter a valid URL",
          title_cannot_be_empty: "Title cannot be empty",
          text_cannot_be_empty: "Text cannot be empty",
          source_removed: "Data source has been removed from your project.",
          post_saved: "Your post content has been saved successfully.",
          failed_to_save_post: "Failed to save post content. Please try again.",
          failed_to_upload_text: "Failed to upload text. Please try again.",
          failed_to_upload_pdf: "Failed to upload PDF. Please try again.",
          failed_to_send_chat_message: "Failed to send chat message",
          failed_to_process_chat_message: "Failed to process chat message",
          failed_to_load_documents: "Failed to load documents",
          chat_history_loaded: "Chat history loaded",
          failed_to_load_chat_history: "Failed to load chat history",
          project_deleted: "Project has been deleted successfully.",
          failed_to_delete_project: "Failed to delete project. Please try again.",
        },
        confirm: {
          delete_document_title: "Delete Document",
          delete_document_message: "Are you sure you want to delete this document? This action cannot be undone.",
          delete_project_title: "Delete Project",
          delete_project_message: "Are you sure you want to delete this project? This action cannot be undone and all project data will be permanently lost.",
          delete: "Delete",
          cancel: "Cancel",
        },
        chat: {
          mock_assistant_response: "I'll help you with that based on your data sources. This is a placeholder response - connect to your AI backend for real responses.",
          processing: "Processing your message...",
          error_message: "Sorry, there was an error processing your message.",
          refresh_history: "Refresh chat history",
        },
      },
      project_editor: {
        view_title: "Post Editor",
        actions: {
          back_to_project: "Back to project",
          open_editor_page: "Open in full editor",
        },
      },
      project_card: {
        status: {
          draft: "Draft",
          in_progress: "In Progress",
          completed: "Completed",
          published: "Published",
          unpublished: "Unpublished",
        },
        created: "Created",
        edit: "Edit",
        save: "Save",
        cancel: "Cancel",
        title_placeholder: "Enter project title...",
        description_placeholder: "Enter project description...",
        toast: {
          saved: "Project updated successfully.",
          error: "Failed to update project. Please try again.",
        },
      },
      profile_view: {
        title: "Profile",
        actions: {
          edit_profile: "Edit Profile",
          cancel: "Cancel",
          save: "Save",
          saving: "Saving...",
          retry: "Retry",
        },
        loading: {
          title: "Loading profile...",
          subtitle: "This may take a moment",
        },
        fields: {
          full_name: "Full Name",
          first_name: "First Name",
          first_name_placeholder: "First Name",
          last_name: "Last Name",
          last_name_placeholder: "Last Name (optional)",
          email_address: "Email Address",
          account_type: "Account Type",
          member_since: "Member Since",
          token_count: "Token Count",
        },
        account_types: {
          free: "Free",
          trial: "Trial",
          paid: "Paid",
          account: "Account",
        },
        errors: {
          first_name_required: "First name is required",
          failed_to_load: "Failed to load profile",
          failed_to_update: "Failed to update profile",
        },
      },
      landing: {
        header: {
          nav_features: "Features",
          nav_how_it_works: "How it Works",
          nav_data_sources: "Data Sources",
          button_sign_in: "Sign In",
          button_get_started: "Get Started",
        },
        hero: {
          badge: "AI-Powered Writing Assistant",
          headline_part1: "Write smarter with",
          headline_part2: "your knowledge",
          subheadline: "Create articles, technical posts, and blog content powered by AI that learns from your personal knowledge base. Upload documents, and let Airticler craft content that sounds like you.",
          cta_start: "Start Writing Free",
          cta_demo: "Watch Demo",
          stats_writers: "Writers",
          stats_articles: "Articles Created",
          stats_satisfaction: "Satisfaction",
        },
        features: {
          section_label: "Features",
          title_part1: "Everything you need to",
          title_part2: "write better",
          description: "Powerful tools designed to enhance your writing workflow and unlock your creative potential.",
          items: {
            ai_learns: {
              title: "AI That Learns You",
              description: "Our AI adapts to your writing style and tone by learning from your uploaded content and preferences.",
            },
            knowledge_stacking: {
              title: "Knowledge Stacking",
              description: "Build layered knowledge bases for different projects. Combine sources for richer, more informed content.",
            },
            smart_generation: {
              title: "Smart Generation",
              description: "Generate full articles, outlines, or specific sections. Control length, tone, and complexity with ease.",
            },
            multi_format: {
              title: "Multi-Format Export",
              description: "Export to Markdown, HTML, Word, or directly publish to your favorite platforms and CMS.",
            },
            private_secure: {
              title: "Private & Secure",
              description: "Your documents and generated content stay private. Enterprise-grade encryption keeps your data safe.",
            },
            lightning_fast: {
              title: "Lightning Fast",
              description: "Generate quality content in seconds, not hours. Spend more time refining and less time waiting.",
            },
          },
        },
        how_it_works: {
          section_label: "How It Works",
          title_part1: "Three steps to",
          title_part2: "brilliant content",
          description: "From upload to publish in minutes, not hours. Here's how Airticler transforms your workflow.",
          step_label: "Step",
          steps: {
            upload: {
              number: "01",
              title: "Upload Your Sources",
              description: "Add PDFs, documents, text files, or paste content directly. Build your personal knowledge base for each project.",
            },
            configure: {
              number: "02",
              title: "Configure Your Project",
              description: "Set your tone, style preferences, target audience, and content type. The AI adapts to your specific needs.",
            },
            generate: {
              number: "03",
              title: "Generate & Refine",
              description: "Create your content with AI assistance. Edit, expand, or regenerate sections until it's perfect.",
            },
          },
        },
        data_sources: {
          section_label: "Data Sources",
          title_part1: "Your knowledge,",
          title_part2: "your content",
          description: "Connect any data source to build a rich knowledge base. Airticler extracts insights from your documents to create content that's uniquely informed by your expertise.",
          sources: {
            pdf: {
              label: "PDF Documents",
              description: "Research papers, reports, ebooks",
            },
            text: {
              label: "Text Files",
              description: "Notes, drafts, outlines",
            },
            markdown: {
              label: "Markdown",
              description: "Technical docs, READMEs",
            },
            web_urls: {
              label: "Web URLs",
              description: "Articles, blog posts, pages",
            },
            databases: {
              label: "Databases",
              description: "Notion, Airtable exports",
            },
            direct_input: {
              label: "Direct Input",
              description: "Paste or type content",
            },
          },
        },
      },
      vuestic: {
        close: "Close",
      },
    },
    ru: {
      common: {
        app_name: "Airticler",
        author_name: "Сергей Сидоров",
        created_date: "2025",
        signin_button_title: "Войти",
        logout_button_title: "Выйти",
        profile_button_title: "Профиль",
        project_button_title: "Проекты",
        refresh_button_title: "Обновить",
        tokens_label: "Баланс",
      },
      home: {
        app_title: "Bass Liner: исследуйте ваши любимые басовые табы",
        app_description: "AI платформа для извлечения басовых табов из ваших любимых песен"
      },
      login: {
        back_to_home: "Вернуться на главную",
        subtitle: "Войдите, чтобы начать создавать удивительный контент",
        welcome_back: "С возвращением",
        continue_with_account: "Продолжить с вашим аккаунтом PM Moscow Club",
        sign_in_button: "Войти через PM Moscow Club",
        terms_notice: "Входя в систему, вы соглашаетесь с нашими Условиями использования и Политикой конфиденциальности",
      },
      new_project: {
        back_to_projects: "Вернуться к проектам",
        title: "Создать новый проект",
        subtitle: "Начните новый проект для написания с помощью AI",
        form: {
          project_title_label: "Название проекта",
          project_title_placeholder: "Введите название проекта...",
          description_label: "Тема поста",
          description_placeholder: "Введите тему вашего поста...",
          description_hint: "Опишите основную тему или тему вашего поста",
          language_label: "Язык поста",
        },
        actions: {
          cancel: "Отмена",
          create: "Создать проект",
          creating: "Создание...",
        },
        toast: {
          title_required: "Пожалуйста, введите название проекта.",
          description_required: "Пожалуйста, введите тему вашего поста.",
          project_created: "Ваш новый проект успешно создан.",
        },
      },
      project_list: {
        title: "Мои Проекты",
        subtitle: "Управляйте и организуйте свои проекты для написания",
        new_project_button: "Новый Проект",
        search_placeholder: "Поиск проектов...",
        stats: {
          total: "Всего:",
          unpublished: "Неопубликовано:",
          published: "Опубликовано:",
        },
        loading: "Загрузка проектов...",
        error_message: "Не удалось загрузить проекты. Пожалуйста, попробуйте позже.",
        retry_button: "Повторить",
        empty_search: "Проекты, соответствующие вашему запросу, не найдены.",
        empty_search_title: "Результаты не найдены",
        empty_state: "Проектов пока нет. Создайте свой первый проект, чтобы начать!",
        empty_state_title: "Создайте свой первый проект",
      },
      project_view: {
        loading: "Загрузка проекта...",
        loading_text: "Загрузка текста поста...",
        sections: {
          data_sources: "Источники данных",
          ai_assistant: "AI помощник",
          post_content: "Текст поста",
        },
        actions: {
          back_to_projects: "Вернуться к проектам",
          retry: "Повторить",
          upload_pdf: "Загрузить PDF",
          upload_document: "Загрузить документ",
          add_text: "Добавить текст",
          add_pdf_url: "Добавить URL PDF",
          add_pdf: "Добавить PDF",
          cancel: "Отмена",
          add_to_rag: "Добавить в RAG",
          save_post: "Сохранить",
          delete_project: "Удалить проект",
          refresh_text: "Обновить текст с сервера",
          open_in_modal: "Открыть в редакторе",
          refresh: "Обновить",
          uploading: "Загрузка...",
          saving: "Сохранение...",
        },
        placeholders: {
          text_to_add_to_knowledge_base: "Введите текст, чтобы добавить его в базу знаний...",
          text_name: "Название текста (обязательно)",
          pdf_name: "Название PDF (обязательно)",
          pdf_url: "Введите URL PDF (например, https://example.com/document.pdf)",
          chat_input: "Задайте вопрос или введите запрос...",
          post_editor: "Начните писать здесь... Используйте AI помощника, чтобы генерировать контент на основе ваших источников данных.",
        },
        validation: {
          invalid_url: "Пожалуйста, введите корректный URL",
        },
        empty: {
          no_data_sources: "Источники данных пока не добавлены",
          chat_prompt: "Задавайте вопросы по вашим источникам данных или попросите помощи с контентом",
        },
        data_sources: {
          text_snippet_name: "Текстовый фрагмент",
        },
        post: {
          characters: "{count} символов",
        },
        defaults: {
          unknown_project: "Неизвестный проект",
          untitled_project: "Проект без названия",
          no_description: "Без описания",
        },
        errors: {
          failed_to_load_project_title: "Не удалось загрузить проект",
          unknown_error: "Неизвестная ошибка",
          unknown_error_occurred: "Произошла неизвестная ошибка",
          project_id_missing: "Отсутствует идентификатор проекта",
          failed_to_load_text: "Не удалось загрузить текст поста. Вы можете редактировать вручную.",
        },
        toast: {
          failed_to_load_project: "Не удалось загрузить проект",
          file_added_to_sources: "{fileName} добавлен в источники данных.",
          text_added_to_rag: "Ваш текст добавлен в базу знаний RAG.",
          pdf_url_added: "URL PDF добавлен в источники данных.",
          invalid_url: "Пожалуйста, введите корректный URL",
          title_cannot_be_empty: "Название не может быть пустым",
          text_cannot_be_empty: "Текст не может быть пустым",
          source_removed: "Источник данных удалён из проекта.",
          post_saved: "Текст поста успешно сохранён.",
          failed_to_save_post: "Не удалось сохранить текст поста. Попробуйте ещё раз.",
          failed_to_upload_text: "Не удалось загрузить текст. Попробуйте ещё раз.",
          failed_to_upload_pdf: "Не удалось загрузить PDF. Попробуйте ещё раз.",
          failed_to_send_chat_message: "Не удалось отправить сообщение в чат",
          failed_to_process_chat_message: "Не удалось обработать сообщение в чате",
          failed_to_load_documents: "Не удалось загрузить документы",
          chat_history_loaded: "История чата загружена",
          failed_to_load_chat_history: "Не удалось загрузить историю чата",
          project_deleted: "Проект успешно удалён.",
          failed_to_delete_project: "Не удалось удалить проект. Попробуйте ещё раз.",
        },
        confirm: {
          delete_document_title: "Удалить документ",
          delete_document_message: "Вы уверены, что хотите удалить этот документ? Это действие нельзя отменить.",
          delete_project_title: "Удалить проект",
          delete_project_message: "Вы уверены, что хотите удалить этот проект? Это действие нельзя отменить, и все данные проекта будут безвозвратно потеряны.",
          delete: "Удалить",
          cancel: "Отмена",
        },
        chat: {
          mock_assistant_response: "Я помогу с этим на основе ваших источников данных. Это заглушка — подключите AI backend, чтобы получать реальные ответы.",
          processing: "Обработка вашего сообщения...",
          error_message: "Извините, произошла ошибка при обработке вашего сообщения.",
          refresh_history: "Обновить историю чата",
        },
      },
      project_editor: {
        view_title: "Редактор поста",
        actions: {
          back_to_project: "Вернуться к проекту",
          open_editor_page: "Открыть в полном редакторе",
        },
      },
      project_card: {
        status: {
          draft: "Черновик",
          in_progress: "В Процессе",
          completed: "Завершено",
          published: "Опубликовано",
          unpublished: "Неопубликовано",
        },
        created: "Создано",
        edit: "Редактировать",
        save: "Сохранить",
        cancel: "Отмена",
        title_placeholder: "Введите название проекта...",
        description_placeholder: "Введите описание проекта...",
        toast: {
          saved: "Проект успешно обновлён.",
          error: "Не удалось обновить проект. Пожалуйста, попробуйте снова.",
        },
      },
      profile_view: {
        title: "Профиль",
        actions: {
          edit_profile: "Редактировать профиль",
          cancel: "Отмена",
          save: "Сохранить",
          saving: "Сохранение...",
          retry: "Повторить",
        },
        loading: {
          title: "Загрузка профиля...",
          subtitle: "Это может занять некоторое время",
        },
        fields: {
          full_name: "Полное имя",
          first_name: "Имя",
          first_name_placeholder: "Имя",
          last_name: "Фамилия",
          last_name_placeholder: "Фамилия (необязательно)",
          email_address: "Адрес электронной почты",
          account_type: "Тип аккаунта",
          member_since: "Участник с",
          token_count: "Количество токенов",
        },
        account_types: {
          free: "Бесплатный",
          trial: "Пробный",
          paid: "Платный",
          account: "Аккаунт",
        },
        errors: {
          first_name_required: "Имя обязательно для заполнения",
          failed_to_load: "Не удалось загрузить профиль",
          failed_to_update: "Не удалось обновить профиль",
        },
      },
      landing: {
        header: {
          nav_features: "Возможности",
          nav_how_it_works: "Как Это Работает",
          nav_data_sources: "Источники Данных",
          button_sign_in: "Войти",
          button_get_started: "Начать",
        },
        hero: {
          badge: "AI-Помощник для Писателей",
          headline_part1: "Пишите умнее с",
          headline_part2: "вашими знаниями",
          subheadline: "Создавайте статьи, технические посты и контент для блогов с помощью AI, который учится на вашей личной базе знаний. Загружайте документы, и пусть Airticler создаст контент, который звучит как вы.",
          cta_start: "Начать Писать Бесплатно",
          cta_demo: "Смотреть Демо",
          stats_writers: "Писателей",
          stats_articles: "Статей Создано",
          stats_satisfaction: "Удовлетворённость",
        },
        features: {
          section_label: "Возможности",
          title_part1: "Всё, что нужно для",
          title_part2: "лучшего письма",
          description: "Мощные инструменты, разработанные для улучшения вашего рабочего процесса письма и раскрытия вашего творческого потенциала.",
          items: {
            ai_learns: {
              title: "AI, Который Изучает Вас",
              description: "Наш AI адаптируется к вашему стилю и тону письма, изучая загруженный вами контент и предпочтения.",
            },
            knowledge_stacking: {
              title: "Накопление Знаний",
              description: "Создавайте многоуровневые базы знаний для разных проектов. Объединяйте источники для более богатого и информированного контента.",
            },
            smart_generation: {
              title: "Умная Генерация",
              description: "Генерируйте полные статьи, планы или конкретные разделы. Легко контролируйте длину, тон и сложность.",
            },
            multi_format: {
              title: "Экспорт в Разные Форматы",
              description: "Экспортируйте в Markdown, HTML, Word или публикуйте напрямую на ваши любимые платформы и CMS.",
            },
            private_secure: {
              title: "Приватно и Безопасно",
              description: "Ваши документы и созданный контент остаются приватными. Шифрование корпоративного уровня защищает ваши данные.",
            },
            lightning_fast: {
              title: "Молниеносно Быстро",
              description: "Генерируйте качественный контент за секунды, а не часы. Тратьте больше времени на доработку и меньше на ожидание.",
            },
          },
        },
        how_it_works: {
          section_label: "Как Это Работает",
          title_part1: "Три шага к",
          title_part2: "блестящему контенту",
          description: "От загрузки до публикации за минуты, а не часы. Вот как Airticler преобразует ваш рабочий процесс.",
          step_label: "Шаг",
          steps: {
            upload: {
              number: "01",
              title: "Загрузите Ваши Источники",
              description: "Добавляйте PDF, документы, текстовые файлы или вставляйте контент напрямую. Создавайте свою личную базу знаний для каждого проекта.",
            },
            configure: {
              number: "02",
              title: "Настройте Ваш Проект",
              description: "Установите тон, стилистические предпочтения, целевую аудиторию и тип контента. AI адаптируется к вашим конкретным потребностям.",
            },
            generate: {
              number: "03",
              title: "Генерируйте и Улучшайте",
              description: "Создавайте контент с помощью AI. Редактируйте, расширяйте или перегенерируйте разделы, пока всё не станет идеальным.",
            },
          },
        },
        data_sources: {
          section_label: "Источники Данных",
          title_part1: "Ваши знания,",
          title_part2: "ваш контент",
          description: "Подключайте любые источники данных для создания богатой базы знаний. Airticler извлекает идеи из ваших документов, чтобы создавать контент, уникально информированный вашей экспертизой.",
          sources: {
            pdf: {
              label: "PDF Документы",
              description: "Исследовательские работы, отчёты, электронные книги",
            },
            text: {
              label: "Текстовые Файлы",
              description: "Заметки, черновики, планы",
            },
            markdown: {
              label: "Markdown",
              description: "Техническая документация, README",
            },
            web_urls: {
              label: "Веб-URL",
              description: "Статьи, посты в блогах, страницы",
            },
            databases: {
              label: "Базы Данных",
              description: "Экспорты из Notion, Airtable",
            },
            direct_input: {
              label: "Прямой Ввод",
              description: "Вставьте или введите контент",
            },
          },
        },
      },
      vuestic: {
        close: "Закрыть",
      },
    },
  };
  
  export default messages;